/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'eiorio' at '7/11/18 11:31 AM' with Gradle 2.14.1
 *
 * @author eiorio, @date 7/11/18 11:31 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
